export const GET_PROJECTS = 'GET_PROJECTS';
export const UPDATE_PROJECTS = 'UPDATE_PROJECTS';
export const ADD_PROJECT_MODAL = 'ADD_PROJECT_MODAL';
export const ADD_KEYWORD_MODAL = 'ADD_KEYWORD_MODAL';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const UPDATE_KEYWORD = 'UPDATE_KEYWORD';
export const UPDATE_PROJECT_LOADING_STATE = 'UPDATE_PROJECT_LOADING_STATE';
