<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZgfQ9mZ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZgfQ9mZ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZgfQ9mZ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZgfQ9mZ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZgfQ9mZ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZgfQ9mZ',
    'container.build_id' => 'f0f6d9f5',
    'container.build_time' => 1558271678,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZgfQ9mZ');
