<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8ErBWxb\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8ErBWxb/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/Container8ErBWxb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\Container8ErBWxb\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \Container8ErBWxb\srcApp_KernelProdContainer([
    'container.build_hash' => '8ErBWxb',
    'container.build_id' => 'c33fe705',
    'container.build_time' => 1557581465,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8ErBWxb');
